name: test_app
description: Test Flutter app.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^2.2.1
  google_fonts: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  

  assets:
    - assets/images/1-1.jpg
    - assets/images/1-2.jpg
    - assets/images/1-3.jpg
    - assets/images/1-4.jpg
    - assets/images/frida.jpg
    - assets/images/graciela1.jpg
    - assets/images/carousel_1.jpg
    - assets/images/carousel_2.jpg
    - assets/images/carousel_3.jpg
    - assets/images/carousel_4.jpg
    - assets/images/carousel_5.jpg
    - assets/images/granny.jpg
    - assets/images/laptop.jpg
    - assets/images/people.jpg
    - assets/images/cali_1.jpg
    - assets/images/cali_2.jpg
    - assets/images/jesi_1.jpg
    - assets/images/jesi_2.jpg
    - assets/images/jesi_3.jpg
    - assets/images/5-1-1.png
    - assets/images/5-1-2.png
    - assets/images/5-2-1.png
    - assets/images/5-2-2.png
    - assets/images/5-3-1.png
    - assets/images/5-3-2.png
    - assets/images/5-4-1.png
    - assets/images/5-4-2.png
    - assets/images/nabilla.png
    - assets/images/7-1.jpg
    - assets/images/7-2.jpg
    - assets/images/7-3.jpg
    - assets/images/7-4.jpg
    - assets/images/7-5.jpg
    - assets/images/7-6.jpg
    - assets/images/7_down.jpg
    - assets/images/8-1.png
    - assets/images/8-2.png
    - assets/images/8-3.png
    - assets/images/8-top-icon.png
    - assets/images/9-beirut.jpg
    - assets/images/9-elwood.png
    - assets/images/9-user-image.png
    - assets/images/10-top-1.jpg
    - assets/images/10-top-2.jpg
    - assets/images/10-top-3.jpg
    - assets/images/10-bottom-1.jpg
    - assets/images/10-bottom-2.jpg
    - assets/images/10-bottom-3.jpg
    - assets/images/10-bottom-4.jpg
    - assets/images/10-bottom-5.jpg
    - assets/images/11_dots.jpg
    - assets/images/11_sound_of_wind.jpg
    - assets/images/11_04_forest_more.jpg
    - assets/images/11_04_forest.png
    - assets/images/11_user.png
